"""add_scheduled_at

Revision ID: 25151490597c
Revises: b2918d099859
Create Date: 2026-04-20 01:44:22.378129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25151490597c'
down_revision: Union[str, None] = 'b2918d099859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'scheduled_at')
    # ### end Alembic commands ###
