"""add vigilance_score to user

Revision ID: 59dd3588705f
Revises: c94f673bcb0c
Create Date: 2026-05-13 21:11:05.122400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dd3588705f'
down_revision: Union[str, None] = 'c94f673bcb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vigilance_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vigilance_score')
    # ### end Alembic commands ###
