"""add xp and level

Revision ID: 64209eaacedf
Revises: 77a1896c6218
Create Date: 2026-04-20 03:29:18.176516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64209eaacedf'
down_revision: Union[str, None] = '77a1896c6218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###
