"""Add channel and points

Revision ID: 77a1896c6218
Revises: 4eed87f8c72a
Create Date: 2026-04-20 02:57:59.555635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a1896c6218'
down_revision: Union[str, None] = '4eed87f8c72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'channel')
    op.drop_column('departments', 'points')
    # ### end Alembic commands ###
