"""add invite_code to departments

Revision ID: 945e5997c006
Revises: 64209eaacedf
Create Date: 2026-04-20 04:08:11.832601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945e5997c006'
down_revision: Union[str, None] = '64209eaacedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('invite_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_departments_invite_code'), 'departments', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_invite_code'), table_name='departments')
    op.drop_column('departments', 'invite_code')
    # ### end Alembic commands ###
