"""Add customization fields

Revision ID: b7a0b3e95ef6
Revises: 945e5997c006
Create Date: 2026-04-22 22:07:54.579796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a0b3e95ef6'
down_revision: Union[str, None] = '945e5997c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('dashboard_layout', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'dashboard_layout')
    op.drop_column('company_settings', 'logo_url')
    # ### end Alembic commands ###
