"""Add text field to simulations

Revision ID: dd28ea21c657
Revises: f85994197703
Create Date: 2026-04-08 10:12:28.567603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd28ea21c657'
down_revision: Union[str, None] = 'f85994197703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'text')
    # ### end Alembic commands ###
