"""Add phishing campaign metrics and targets

Revision ID: f85994197703
Revises: 5388b8019af2
Create Date: 2026-04-08 09:26:08.871240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85994197703'
down_revision: Union[str, None] = '5388b8019af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('total_targets', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('total_clicks', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('total_opened', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('total_reported', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'total_reported')
    op.drop_column('simulations', 'total_opened')
    op.drop_column('simulations', 'total_clicks')
    op.drop_column('simulations', 'total_targets')
    # ### end Alembic commands ###
